openapi: 3.0.0
info:
  version: 1.0.0
  title: Back End Demonstration API
  description: A simple blog API.
  contact:
    name: Kwok Chun Hang
    email: kwokc289@yahoo.com
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

servers:
  - url: "http://localhost:10888"
    description: Development server

tags:
  - name: Users
    description: API endpoints for user management.
  - name: Articles
    description: Access and perform CRUD operations for blog

paths:
  /articles:
    post:
      tags:
        - Articles
      description: Create a new article
      requestBody:
        description: The article information to be added
        required: true
        content:
          application/json:
            schema:
              $ref: "./article.json#/definitions/article"
      responses:
        "201":
          description: Successfully created article
        "400":
          description: Request format error

  /articles/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        description: The numeric ID of the article
    get:
      tags:
        - Articles
      description: Get article by ID
      responses:
        "200":
          description: Found the article
        "404":
          description: Article not found
    put:
      tags:
        - Articles
      description: Update article by ID
      requestBody:
        description: The article information to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: "./article.json#/definitions/article"
      responses:
        "200":
          description: Successfully updated the article
        "400":
          description: Request data error
        "404":
          description: Article not found
    delete:
      tags:
        - Articles
      description: Delete article by ID
      responses:
        "200":
          description: Successfully deleted the article
        "404":
          description: Article not found
