openapi: 3.0.0
info:
  version: 1.0.0
  title: Back End Demonstration API
  description: A simple blog API.
  contact:
    name: Kwok Chun Hang
    email: kwokc289@yahoo.com
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"

servers:
  - name: Users
    description: API endpoints for user management.

  - url: "http://localhost:10888"
    description: Development server

tags:
  - name: Articles
    description: 操作文章的 API

paths:
  /articles:
    post:
      tags:
        - Articles
      description: 建立新文章
      requestBody:
        description: 要新增的文章資料
        required: true
        content:
          application/json:
            schema:
              $ref: "./article.json#/definitions/article"
      responses:
        "201":
          description: 成功建立文章
        "400":
          description: 請求格式錯誤

  /articles/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        description: 文章的數字 ID
    get:
      tags:
        - Articles
      description: 根據 ID 取得文章
      responses:
        "200":
          description: 找到文章
        "404":
          description: 找不到文章
    put:
      tags:
        - Articles
      description: 根據 ID 更新文章
      requestBody:
        description: 要更新的文章資料
        required: true
        content:
          application/json:
            schema:
              $ref: "./article.json#/definitions/article"
      responses:
        "200":
          description: 成功更新文章
        "400":
          description: 請求資料錯誤
        "404":
          description: 找不到文章
    delete:
      tags:
        - Articles
      description: 根據 ID 刪除文章
      responses:
        "200":
          description: 成功刪除文章
        "404":
          description: 找不到文章
